name: docker build

on:
  schedule:
    - cron: "15,45 * * * *"
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          df -h
          set -ex
          wget -qO- https://raw.githubusercontent.com/apache/flink/271ef7b7dfac195b43abced8b81c38998855dabf/tools/azure-pipelines/free_disk_space.sh | bash
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Cleanup Disk
        uses: curoky/cleanup-disk-action@v2.0
        with:
          retain: ""
      - name: Check space left
        run: |
          df -h
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.2.0
        with:
          images: quay.io/sim/sponsorblockdb
          flavor: |
            latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,prefix=,format=long,event=branch
            type=ref,event=tag
            type=sha,prefix=,format=long,event=tag
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: sim
          password: ${{ secrets.MY_QUAY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
